// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250424082706_suffix")]
    partial class suffix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Shared.Models.AccessCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccessCards");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.LimitValueAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LimitValueId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("LimitValueId");

                    b.ToTable("LimitValueAssignment");

                    b.HasDiscriminator<string>("type").HasValue("LimitValueAssignment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TimeLimitId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("TimeLimitId");

                    b.ToTable("TimeLimitAssignment");

                    b.HasDiscriminator<string>("type").HasValue("TimeLimitAssignment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Shared.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CadastreId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CadastreId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Shared.Models.Cadastre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cadastres");
                });

            modelBuilder.Entity("Shared.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SectionId");

                    b.HasIndex("TypeId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Shared.Models.DeviceData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TypeId");

                    b.ToTable("DeviceDatas");
                });

            modelBuilder.Entity("Shared.Models.DeviceDataLimitValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("MaximumLimit")
                        .HasColumnType("double");

                    b.Property<double>("MinimumLimit")
                        .HasColumnType("double");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("DeviceDataLimit");
                });

            modelBuilder.Entity("Shared.Models.DeviceDataType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Suffix")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DeviceDataTypes");
                });

            modelBuilder.Entity("Shared.Models.DeviceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TypeId");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("Shared.Models.DeviceEventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DeviceEventTypes");
                });

            modelBuilder.Entity("Shared.Models.DeviceInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TypeId");

                    b.ToTable("DeviceInfos");
                });

            modelBuilder.Entity("Shared.Models.DeviceInfoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DeviceInfoTypes");
                });

            modelBuilder.Entity("Shared.Models.DeviceMqttMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DataTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("InfoTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataTypeId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("InfoTypeId");

                    b.ToTable("DeviceMqttMaps");
                });

            modelBuilder.Entity("Shared.Models.DeviceRecording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Converted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<float?>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Finished")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceRecordings");
                });

            modelBuilder.Entity("Shared.Models.DeviceSharedCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeviceSharedCategories");
                });

            modelBuilder.Entity("Shared.Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("Shared.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Shared.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("SectionId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Shared.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SecurityGroups");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("SecurityGroupDevices");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("SecurityGroupPermissions");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("SecurityGroupRooms");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("SecurityGroupId");

                    b.ToTable("SecurityGroupSections");
                });

            modelBuilder.Entity("Shared.Models.TimeLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TimeLimits");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TimeLimitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TimeLimitId");

                    b.ToTable("TimeLimitWeeks");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeekDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeekId");

                    b.ToTable("TimeLimitWeekDays");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeekDayTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FromTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ToTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("WeekDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WeekDayId");

                    b.ToTable("TimeLimitWeekDayTimes");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HashedPassword")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("longtext");

                    b.Property<string>("ResetState")
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.Models.UserDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("Shared.Models.UserRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRooms");
                });

            modelBuilder.Entity("Shared.Models.UserSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSections");
                });

            modelBuilder.Entity("Shared.Models.UserSecurityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SecurityGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecurityGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSecurityGroups");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.BuildingLV", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.LimitValues.LimitValueAssignment");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasIndex("BuildingId");

                    b.HasDiscriminator().HasValue("building");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.CadastreLV", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.LimitValues.LimitValueAssignment");

                    b.Property<int>("CadastreId")
                        .HasColumnType("int");

                    b.HasIndex("CadastreId");

                    b.HasDiscriminator().HasValue("cadastre");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.RoomLV", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.LimitValues.LimitValueAssignment");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("room");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.SectionLV", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.LimitValues.LimitValueAssignment");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasIndex("SectionId");

                    b.HasDiscriminator().HasValue("section");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.SecurityGroupDeviceTL", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment");

                    b.Property<int>("SecurityGroupDeviceId")
                        .HasColumnType("int");

                    b.HasIndex("SecurityGroupDeviceId");

                    b.HasDiscriminator().HasValue("secgrp_device");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.SecurityGroupRoomTL", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment");

                    b.Property<int>("SecurityGroupRoomId")
                        .HasColumnType("int");

                    b.HasIndex("SecurityGroupRoomId");

                    b.HasDiscriminator().HasValue("secgrp_room");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.SecurityGroupSectionTL", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment");

                    b.Property<int>("SecurityGroupSectionId")
                        .HasColumnType("int");

                    b.HasIndex("SecurityGroupSectionId");

                    b.HasDiscriminator().HasValue("secgrp_section");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.UserDeviceTL", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment");

                    b.Property<int>("UserDeviceId")
                        .HasColumnType("int");

                    b.HasIndex("UserDeviceId");

                    b.HasDiscriminator().HasValue("user_device");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.UserRoomTL", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment");

                    b.Property<int>("UserRoomId")
                        .HasColumnType("int");

                    b.HasIndex("UserRoomId");

                    b.HasDiscriminator().HasValue("user_room");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.UserSectionTL", b =>
                {
                    b.HasBaseType("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment");

                    b.Property<int>("UserSectionId")
                        .HasColumnType("int");

                    b.HasIndex("UserSectionId");

                    b.HasDiscriminator().HasValue("user_section");
                });

            modelBuilder.Entity("Shared.Models.AccessCard", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("AccessCards")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.LimitValueAssignment", b =>
                {
                    b.HasOne("Shared.Models.DeviceDataLimitValue", "LimitValue")
                        .WithMany()
                        .HasForeignKey("LimitValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LimitValue");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.TimeLimitAssignment", b =>
                {
                    b.HasOne("Shared.Models.TimeLimit", "TimeLimit")
                        .WithMany("Assignments")
                        .HasForeignKey("TimeLimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeLimit");
                });

            modelBuilder.Entity("Shared.Models.Building", b =>
                {
                    b.HasOne("Shared.Models.Cadastre", "Cadastre")
                        .WithMany("Buildings")
                        .HasForeignKey("CadastreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastre");
                });

            modelBuilder.Entity("Shared.Models.Device", b =>
                {
                    b.HasOne("Shared.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId");

                    b.HasOne("Shared.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId");

                    b.HasOne("Shared.Models.DeviceType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Section");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Shared.Models.DeviceData", b =>
                {
                    b.HasOne("Shared.Models.Device", "Device")
                        .WithMany("Data")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.DeviceDataType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Shared.Models.DeviceDataLimitValue", b =>
                {
                    b.HasOne("Shared.Models.DeviceDataType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Shared.Models.DeviceDataType", b =>
                {
                    b.HasOne("Shared.Models.DeviceSharedCategory", "Category")
                        .WithMany("DataTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.DeviceEvent", b =>
                {
                    b.HasOne("Shared.Models.Device", "Device")
                        .WithMany("Events")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.DeviceEventType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Shared.Models.DeviceEventType", b =>
                {
                    b.HasOne("Shared.Models.DeviceSharedCategory", "Category")
                        .WithMany("EventTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.DeviceInfo", b =>
                {
                    b.HasOne("Shared.Models.Device", "Device")
                        .WithMany("Infos")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.DeviceInfoType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Shared.Models.DeviceInfoType", b =>
                {
                    b.HasOne("Shared.Models.DeviceSharedCategory", "Category")
                        .WithMany("InfoTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Shared.Models.DeviceMqttMap", b =>
                {
                    b.HasOne("Shared.Models.DeviceDataType", "DataType")
                        .WithMany()
                        .HasForeignKey("DataTypeId");

                    b.HasOne("Shared.Models.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.DeviceInfoType", "InfoType")
                        .WithMany()
                        .HasForeignKey("InfoTypeId");

                    b.Navigation("DataType");

                    b.Navigation("DeviceType");

                    b.Navigation("InfoType");
                });

            modelBuilder.Entity("Shared.Models.DeviceRecording", b =>
                {
                    b.HasOne("Shared.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Shared.Models.Room", b =>
                {
                    b.HasOne("Shared.Models.Building", null)
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId");

                    b.HasOne("Shared.Models.Section", "Section")
                        .WithMany("Rooms")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Shared.Models.Section", b =>
                {
                    b.HasOne("Shared.Models.Building", "Building")
                        .WithMany("Sections")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupDevice", b =>
                {
                    b.HasOne("Shared.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.SecurityGroup", "SecurityGroup")
                        .WithMany()
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupPermission", b =>
                {
                    b.HasOne("Shared.Models.Permission", "Permission")
                        .WithMany("SecurityGroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("SecurityGroupPermissions")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupRoom", b =>
                {
                    b.HasOne("Shared.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.SecurityGroup", "SecurityGroup")
                        .WithMany()
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupSection", b =>
                {
                    b.HasOne("Shared.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.SecurityGroup", "SecurityGroup")
                        .WithMany()
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("SecurityGroup");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeek", b =>
                {
                    b.HasOne("Shared.Models.TimeLimit", "TimeLimit")
                        .WithMany("Weeks")
                        .HasForeignKey("TimeLimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeLimit");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeekDay", b =>
                {
                    b.HasOne("Shared.Models.TimeLimitWeek", "Week")
                        .WithMany("Days")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Week");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeekDayTime", b =>
                {
                    b.HasOne("Shared.Models.TimeLimitWeekDay", "WeekDay")
                        .WithMany("Times")
                        .HasForeignKey("WeekDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeekDay");
                });

            modelBuilder.Entity("Shared.Models.UserDevice", b =>
                {
                    b.HasOne("Shared.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.UserRoom", b =>
                {
                    b.HasOne("Shared.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.UserSection", b =>
                {
                    b.HasOne("Shared.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.UserSecurityGroup", b =>
                {
                    b.HasOne("Shared.Models.SecurityGroup", "SecurityGroup")
                        .WithMany("UserSecurityGroups")
                        .HasForeignKey("SecurityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("UserSecurityGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.BuildingLV", b =>
                {
                    b.HasOne("Shared.Models.Building", "Building")
                        .WithMany("LimitValues")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.CadastreLV", b =>
                {
                    b.HasOne("Shared.Models.Cadastre", "Cadastre")
                        .WithMany("LimitValues")
                        .HasForeignKey("CadastreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastre");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.RoomLV", b =>
                {
                    b.HasOne("Shared.Models.Room", "Room")
                        .WithMany("LimitValues")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Shared.Models.Assignables.LimitValues.SectionLV", b =>
                {
                    b.HasOne("Shared.Models.Section", "Section")
                        .WithMany("LimitValues")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.SecurityGroupDeviceTL", b =>
                {
                    b.HasOne("Shared.Models.SecurityGroupDevice", "SecurityGroupDevice")
                        .WithMany("TimeLimits")
                        .HasForeignKey("SecurityGroupDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroupDevice");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.SecurityGroupRoomTL", b =>
                {
                    b.HasOne("Shared.Models.SecurityGroupRoom", "SecurityGroupRoom")
                        .WithMany("TimeLimits")
                        .HasForeignKey("SecurityGroupRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroupRoom");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.SecurityGroupSectionTL", b =>
                {
                    b.HasOne("Shared.Models.SecurityGroupSection", "SecurityGroupSection")
                        .WithMany("TimeLimits")
                        .HasForeignKey("SecurityGroupSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGroupSection");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.UserDeviceTL", b =>
                {
                    b.HasOne("Shared.Models.UserDevice", "UserDevice")
                        .WithMany("TimeLimits")
                        .HasForeignKey("UserDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDevice");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.UserRoomTL", b =>
                {
                    b.HasOne("Shared.Models.UserRoom", "UserRoom")
                        .WithMany("TimeLimits")
                        .HasForeignKey("UserRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRoom");
                });

            modelBuilder.Entity("Shared.Models.Assignables.TimeLimit.UserSectionTL", b =>
                {
                    b.HasOne("Shared.Models.UserSection", "UserSection")
                        .WithMany("TimeLimits")
                        .HasForeignKey("UserSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSection");
                });

            modelBuilder.Entity("Shared.Models.Building", b =>
                {
                    b.Navigation("LimitValues");

                    b.Navigation("Rooms");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Shared.Models.Cadastre", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("LimitValues");
                });

            modelBuilder.Entity("Shared.Models.Device", b =>
                {
                    b.Navigation("Data");

                    b.Navigation("Events");

                    b.Navigation("Infos");
                });

            modelBuilder.Entity("Shared.Models.DeviceSharedCategory", b =>
                {
                    b.Navigation("DataTypes");

                    b.Navigation("EventTypes");

                    b.Navigation("InfoTypes");
                });

            modelBuilder.Entity("Shared.Models.Permission", b =>
                {
                    b.Navigation("SecurityGroupPermissions");
                });

            modelBuilder.Entity("Shared.Models.Room", b =>
                {
                    b.Navigation("LimitValues");
                });

            modelBuilder.Entity("Shared.Models.Section", b =>
                {
                    b.Navigation("LimitValues");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroup", b =>
                {
                    b.Navigation("SecurityGroupPermissions");

                    b.Navigation("UserSecurityGroups");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupDevice", b =>
                {
                    b.Navigation("TimeLimits");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupRoom", b =>
                {
                    b.Navigation("TimeLimits");
                });

            modelBuilder.Entity("Shared.Models.SecurityGroupSection", b =>
                {
                    b.Navigation("TimeLimits");
                });

            modelBuilder.Entity("Shared.Models.TimeLimit", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeek", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("Shared.Models.TimeLimitWeekDay", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Navigation("AccessCards");

                    b.Navigation("UserSecurityGroups");
                });

            modelBuilder.Entity("Shared.Models.UserDevice", b =>
                {
                    b.Navigation("TimeLimits");
                });

            modelBuilder.Entity("Shared.Models.UserRoom", b =>
                {
                    b.Navigation("TimeLimits");
                });

            modelBuilder.Entity("Shared.Models.UserSection", b =>
                {
                    b.Navigation("TimeLimits");
                });
#pragma warning restore 612, 618
        }
    }
}
